name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Minify JS
        uses: nizarmah/auto-minify@v1.9
        with:
          directory: 'js'

      - name: Minify CSS
        uses: nizarmah/auto-minify@v1.9
        with:
          directory: 'css'

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.4.1
        with:
          # Commit message
          commit_message: 'GitHub Action: Auto-minified JS and CSS files'
          # Git branch name, where changes should be pushed too. Required if Action is used on the `pull_request` event
          branch: ${{ github.ref }}
